### ISSUE TITLE
How to move forward now that Apache has attic'd Lucy?

### ISSUE THREAD

**Issue by ttkciar** [karpet/dezi-app#24]
I apologize if this isn't the appropriate place for this.  I've tried to contact you through other channels but can't seem to find you.

Apache moved the Lucy project to the "attic" in 2018, and the project has been unmaintained since.  It still works great (builds/runs on modern OSes) but that won't last forever.

Have you given any thought to how to maintain Dezi going forward, either using a different indexing engine or maintaining Lucy (or finding someone else to maintain Lucy)?

**Comment by karpet** [comment]
This is a fine place to reach me. I'm not on IRC much any more, but karpet at dezi dot org should also reach me and the mailing list is still alive afaik https://groups.google.com/forum/#!forum/dezi-search.

[I was the one who initiated moving Lucy to the attic](https://lists.apache.org/list.html?dev@lucy.apache.org:2018-4), since it lacked a critical mass of maintainers. The 3 of us who were left agreed that we would fork the code to https://github.com/lucysearch and if there were any patches required for Perl updates, etc, we could maintain it there. That was nearly 2 years ago and there hasn't yet been a need to patch anything afaik.

I recently pushed some changes to this repo, so Dezi isn't dead. But it is what it always has been: an open source project driven by those with an itch to scratch. I haven't used it in any production contexts for 5+ years since I left the job where I developed most of it. If others are using it, I'm glad it's been of use. As [I wrote about it 6 years ago](http://blogs.perl.org/users/karpet/2014/04/doozi-dezi-moose.html) I haven't really heard from anyone interested in helping with the project, despite a rewrite to make it more community-friendly.

So no: I haven't thought about how to maintain it, beyond the catch-as-catch-can method most open source projects are maintained.

Do you have any suggestions?

**Comment by ttkciar** [comment]
"Catch as catch can" is fine by me!  If I had my druthers, I would like to see Lucy continue to be used for Dezi and other applications, and based on what you say that appears to be the plan.  It is my go-to indexing solution for a handful of personal projects.

I didn't know about the lucysearch fork.  Thank you for putting it on my radar.

Since the Apache attic page for Lucy https://attic.apache.org/projects/lucy.html states "if you should choose to fork Lucy outside of Apache, please let us know so we can link to your project", and there were no links provided, I assumed there were none.  I'm very glad there is one!

I am in the habit of occasionally building/testing Lucy in the latest CentOS and Slackware64-current environments just to make sure it still works.  So far it still does.  If that ever changes, I might offer a pull request to the lucysearch fork.

Last year I suggested using Lucy for a work project, and my manager declined, pointing out that the project is unsupported.  We ended up using RedisSearch instead.  Perhaps if the lucysearch repo shows signs of life and the Apache attic page for Lucy links to it, that might be sufficient to convince him to allow use of Lucy here.

Anyway, thank you for the informative reply!  It's exactly what I wanted to know, and I am pleased that the project isn't quite as completely abandoned as I feared.
